export { default as About } from './About'
export { default as Books } from './Books'
export { default as News } from './News'
export { default as History } from './History'
export { default as HomeLayout } from './HomeLayout'
export { default as Team } from './Team'
export { default as Landing } from './Landing'
export { default as Error } from './Error'
